dashboard/urls.py
# Django Modules
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Third Party Modules
from rest_framework import routers

# App Modules
from api.views import MeasurementViewSet, UserViewSet


router = routers.DefaultRouter()
router.register('^measurements', MeasurementViewSet)
router.register('^users', UserViewSet)


urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'dashboard.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include(router.urls)),
    url(r'^', include('accounts.urls')),
    url(r'^', include('www.urls')),
    url(r'^status/', include('measurements.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns(
    'www.views',
    url(r'^$', 'stream', name='stream'),
)

accounts/models.py
# Django Modules
from django.contrib.auth.models import AbstractUser
from django.db import models

# App Modules


class Country(models.Model):
    """
    Country
    """
    name = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=220, null=True, blank=True)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_updated = models.DateTimeField(auto_now_add=True, auto_now=True)

    def __str__(self):
        return self.code


class State(models.Model):
    """
    STATE
    """
    name = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=220, null=True, blank=True)
    country = models.ForeignKey(Country, blank=True, null=True)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_updated = models.DateTimeField(auto_now_add=True, auto_now=True)

    def __str__(self):
        return self.code


class City(models.Model):
    """
    CITY
    """
    name = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=220, null=True, blank=True)
    state = models.ForeignKey(State, blank=True, null=True)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_updated = models.DateTimeField(auto_now_add=True, auto_now=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    """
    SystemUser
    """
    photo = models.ImageField(upload_to='profiles', blank=True, null=True)
    is_specialist = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    is_relative = models.BooleanField(default=False)
    date_birth = models.DateField(null=True, blank=True)
    genre = models.CharField(max_length=2, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)
    zip_code = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    mobile_phone = models.CharField(max_length=200, null=True, blank=True)
    website = models.CharField(max_length=200, null=True, blank=True)
    work_phone = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=1000, null=True, blank=True)
    institute = models.ForeignKey('specialist.Institute', related_name='institute_user', null=True, blank=True, default=None)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.username

advices/models.py
# Django Modules
from django.db import models

# App Modules
from accounts.models import User


class TipCategory(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=220, null=True, blank=True)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_updated = models.DateTimeField(auto_now_add=True, auto_now=True)


class Tip(models.Model):
    title = models.CharField(max_length=5000, blank=True)
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User)
    category = models.ForeignKey(TipCategory, blank=True, null=True)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_updated = models.DateTimeField(auto_now_add=True, auto_now=True)

accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm


class signin_form(forms.Form):
    email = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class signup_form(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

templates/dashboard/home.html
{% extends 'base_dashboard.html' %}
{% load staticfiles %}
{% block content %}

<div id="contentHeader">
  <h1 style="margin-left: 100px;">  {{ name }} </h1>
       <img  id="img-perfil" class="round-img" height="70" width="70"  src="images/gallery/rain_small.jpg" alt="" />

					      <div id="quickNav">
								<ul>
								<li class="quickNavMail">
									<a href="#menuAmpersand" class="menu"><span class="icon-book"></span></a>		
									
									<span class="alert">1</span>		

									<div id="menuAmpersand" class="menu-container quickNavConfirm">
										<div class="menu-content cf">							
											
											<div class="qnc qnc_confirm">
												
												<h3>Solicitudes</h3>
										
												<div class="qnc_item">
	 											<div class="qnc_content">
														<span class="qnc_title">Confirm #1</span>
														<span class="qnc_preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</span>
														<span class="qnc_time">3 hours ago</span>
													</div> <!-- .qnc_content -->
												
											  	<div class="qnc_actions">						
														<button class="btn btn-primary btn-small">Accept</button>
														<button class="btn btn-quaternary btn-small">Not Now</button>
													</div>
												</div>												
												
										</div>
									</div>
								</li>

							</ul>		
						</div> <!-- .quickNav -->

       	<div id="topNav">
		  <ul>
		 	<li>
		 	 <!--	<a href="#menuProfile" class="menu">John Doe</a>	-->
		 		<div id="menuProfile" class="menu-container menu-dropdown">
					<div class="menu-content">
						<ul class="">
							<li><a href="javascript:;">Edit Profile</a></li>
							<li><a href="javascript:;">Edit Settings</a></li>
							<li><a href="javascript:;">Suspend Account</a></li>
						</ul>
					</div>
				</div>
	 		</li>
		 	<!-- <li><a href="javascript:;">Upgrade</a></li> -->
		  <!--	<li><a href="index.html">Logout</a></li> -->
		 </ul>
	</div> <!-- #topNav -->

		</div> <!-- #contentHeader -->	
		
		<div class="container">
			
			
			<div class="grid-17">
				
				<div class="widget widget-plain">
					
					<div class="widget-content">
				
						<h2 class="dashboard_title">
							Informacion rapida
							<!-- <span>For the week of Jun 15 - Jun 22, 2011</span> -->
						</h2>				
						
						<div class="dashboard_report first activeState">
							<div class="pad">
								<span class="value"> {{ information.healt_points }} </span> Puntos de salud
              </div> <!-- .pad -->
						</div>
						
						<div class="dashboard_report defaultState">
							<div class="pad">
                <span class="value"> {{ information.ideal_heart_rate }} </span> Ideal Heart Rate
							</div> <!-- .pad -->
						</div>

            <div class="dashboard_report defaultState">
							<div class="pad">
                <span class="value"> {{ information.current_bpm }} </span> Actual Heart Rate
							</div> <!-- .pad -->
						</div>

            <div class="dashboard_report defaultState last">
							<div class="pad">
								<span class="value">  {{ information.current_average_effort }} % </span> Esfuerzo Actual
							</div> <!-- .pad -->
						</div>
																
					</div> <!-- .widget-content -->
					
				</div> <!-- .widget -->
         			
				<div class="widget widget-tabs">
          					
					<div class="widget-header">
						<span class="icon-chart"></span>
						<h3 class="">Tus Consejos</h3>	
          
            <!-- Only to 3 tips.. knife style -->
						<ul class="tabs right">	
							<li class="active"><a href="#tip1">Uno</a></li>	
							<li class=""><a href="#tip2">Dos</a></li>					
							<li class=""><a href="#tip3">Tres</a></li>
						</ul>
          
					</div>
          
          {% for tip in tips %}
          
            <div id="tip{{ forloop.counter }}"  class="widget-content">
          
                <h3>{{ tip.name }} </h3>
          
                {{tip.tip}} 
          
            </div> 
          
          {% endfor %}
          
				</div> <!-- .widget -->
          				
			</div> <!-- .grid -->			
          		
{% endblock %}

templates/dashboard/idealrate.html
{% extends 'base_dashboard.html' %}
{% load staticfiles %}
{% block content %}

<div class="page-title">
   <i class=""></i>
   <h3>
      Tu Estado - <span class="semi-bold">Latido Ideal</span>
   </h3>
</div>
<div class="row">
<div class="col-md-6">
   <div class="grid simple transparent">
      <div class="tiles green p-t-15 p-b-15 p-l-25 ">
         <h4><span class="bold">Que es?</span></h4>
         <div class="tools">
            <a href="javascript:;" class="collapse"></a>
            <a href="javascript:;" class="remove"></a>
         </div>
      </div>
      <div class="grid-body" style="overflow: hidden; display: block;">
         <p>
         Tu rate ideal es de {{information.ideal_heart_rate}} latidos por minuto, eres mas saludable si en reposo tu rate no sobrepasa este limite constantemente
         </p>
         <p> Segun una serie de caracteristicas especificas de cada persona el corazon tiene un numero de latidos promedio que te puede indicar que san bien te encuentras verificalo!  </p>
         <div class="blog-bar">
            <a href="#"><i class="icon-eye-open"></i></a> <a href="#"><i class="icon-comment"></i></a>
         </div>
      </div>
   </div>
</div>
<div class="col-md-6 hidden-xlg">
   <div class="row tiles-container  m-b-20 hidden-xlg">
      <div class="m-l-10 ">
         <div class="tiles green p-t-15 p-b-15 p-l-25 ">
            <h5 class="text-black semi-bold">Concejo</h5>
         </div>
         <div class="tiles white ">
            <div class="p-t-20 p-b-15 b-b b-grey">
               <div class="post overlap-left-10">
                  <div class="user-profile-pic-wrapper">
                     <div class="user-profile-pic-wrapper">
                        <div class="user-profile-pic-2x tiles grey white-border">
                           <div class="text-grey inherit-size p-t-10 p-l-10"> <i class="fa fa-heart-o fa-lg"></i> </div>
                        </div>
                     </div>
                  </div>
                  <div class="info-wrapper small-width inline">
                     <div class="info text-black ">
                        <p>{{temptip.title}} </p>
                        <p class="muted small-text"> {{temptip.user.first_name}} {{temptip.user.last_name}} , {{temptip.description}} </p>
                     </div>
                     <div class="clearfix"></div>
                  </div>
                  <div class="inline pull-right">
                     <div class="tiles white p-t-5 p-l-5 p-b-5 p-r-5 inline"> </div>
                  </div>
                  <div class="clearfix"></div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="row">
<div class="col-md-6">
   <div class="grid simple transparent">
      <div class="tiles green p-t-15 p-b-15 p-l-25 ">
         <h4><span class="bold">Detalles</span></h4>
         <div class="tools">
            <a href="javascript:;" class="collapse"></a>
            <a href="javascript:;" class="remove"></a>
         </div>
      </div>
      <div class="grid-body" style="overflow: hidden; display: block;">
         <p>
            En esta simple grafica puedes observar tu evolución, recuerda si constantemente tus lecturas estan por arriba de lo recomendado consulta a tu médico.
         </p>
         <div id="graph" ></div>
      </div>
   </div>
</div>
<div class="col-md-6">
<div class="grid simple transparent">
   <div >
      <h4><span class="bold"></span></h4>
      <div class="tools">
         <a href="javascript:;" class="collapse"></a>
         <a href="javascript:;" class="remove"></a>
      </div>
   </div>
   <div class="grid-body" style="overflow: hidden; display: block;">
      <div class="col-md-12 col-sm-6">
         <div class="live-tile slide ha m-b-20 carousel" data-speed="1750" data-delay="8000" data-mode="carousel">
            <div class="slide-front ha tiles green added-margin  slide active" style="-webkit-transition: 750ms ease; transition: 750ms ease; -webkit-transform: translate(0%, 0%) translateZ(0px);">
               <div class="p-t-15 p-l-15 p-r-15 p-b-15">
                  <h4 class="text-black no-margin semi-bold">Información Rapida</h4>
                  <h2 class="text-white no-margin p-t-15 bold">  <span data-animation-duration="900" data-value="60%" class="animate-number">0</span>  </h2>
                  <p class="text-white  p-b-5"></p>
                  <div class="progress transparent progress-small">
                     <div class="progress-bar progress-bar-white animate-progress-bar" data-percentage="70.0%" style="width: 26.8%;"></div>
                  </div>
                  
                  <div class="overlayer bottom-right">
                     <div class="p-r-15 p-b-15"> <i class="fa fa-globe fa fa-5x"></i> </div>
                  </div>
               </div>
            </div>
            <div class="slide-back ha tiles green added-margin slide" style="-webkit-transform: translate(0%, -100%) translateZ(0px); -webkit-transition: 750ms ease; transition: 750ms ease;">
               <div class="p-t-15 p-l-15 p-r-15 p-b-15">
                  <h4 class="text-black no-margin semi-bold">¿Que es?</h4>
               </div>
               <div class="overlayer bottom-left fullwidth">
                  <div class="overlayer-wrapper">
                     <div class="p-t-20 p-l-20 p-r-20 p-b-20">
                        <p class="bold">  </p>
                        <p>  </p>
                        <p class="bold p-t-15"> La barra completamente llena indica que constantemente te encuentras en un nivel normal </p>
                        <p>  </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="clearfix"></div>
      </div>
   </div>
</div>


</div>
    
    <!-- <div class="col-md-16" id="graph" > </div> -->

          
  <script>

        new Morris.Line({
            element: 'graph',
            data: [
                    {% for item in bpms %}
                    { period: '{{ item.date_created }}', ideal: '90' , rate: '{{item.bpm}}' }{% if not forloop.last %},{% endif %}
                    {% endfor %}
            ],
            xkey: 'period',
            ykeys: ['ideal', 'rate'],
            labels: ['Tu rate Ideal', 'Tu Rate'],
            xLabels: "day"
        });

  </script>

{% endblock %}

templates/dashboard/login.html
{% if form.errors %}
 <p class="error"> Error  </p>
{% endif %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<meta charset="utf-8" />
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="" name="description" />
<meta content="" name="author" />
<!-- BEGIN CORE CSS FRAMEWORK -->
<link href="{% static "assets/plugins/pace/pace-theme-flash.css" %}" rel="stylesheet" type="text/css" media="screen"/>
<link href="{% static "assets/plugins/boostrapv3/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/plugins/boostrapv3/css/bootstrap-theme.min.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/plugins/font-awesome/css/font-awesome.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/animate.min.css" %}" rel="stylesheet" type="text/css"/>
<!-- END CORE CSS FRAMEWORK -->
<!-- BEGIN CSS TEMPLATE -->
<link href="{% static "assets/css/style.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/responsive.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/custom-icon-set.css" %}" rel="stylesheet" type="text/css"/>
<!-- END CSS TEMPLATE -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="error-body no-top lazy"  data-original="{% static "assets/img/work.jpg" %} "  style="background-image: url('{% static "assets/img/work.jpg" %}')"> 
<div class="container">
  <div class="row login-container animated fadeInUp">  
        <div class="col-md-7 col-md-offset-2 tiles white no-padding">
		 <div class="p-t-30 p-l-40 p-b-20 xs-p-t-10 xs-p-l-10 xs-p-b-10"> 
          <h2 class="normal"> Bienvenido </h2>
          <p class="p-b-20">Prevenir siempre es mejor.</p>
        </div>
		<div class="tiles grey p-t-20 p-b-20 text-black">
		
      <form action="{% url 'signin' %}" method="post" accept-charset="utf-8" id="frm_login" class="animated fadeIn" >		
        	 {% csrf_token %}

    <div class="row form-row m-l-20 m-r-20 xs-m-l-10 xs-m-r-10">
                      <div class="col-md-6 col-sm-6 ">
                        <input name="email" id="username" type="text"  class="form-control" placeholder="Username">
                      </div>
                      <div class="col-md-6 col-sm-6">
                        <input name="password" id="password" type="password"  class="form-control" placeholder="Password">
                      </div>
                    </div>

			<div class="login_actions">
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
        <button type="submit"  class="btn btn-primary btn-cons" id="login_toggle" >Login</button>
        or
        &nbsp;
        <a href="/dashboard/register"> <button type="button" class="btn btn-info btn-cons" id="register_toggle"> Crear Cuenta</button> </a>
			</div>
		</form>

		</div>   
      </div>   
  </div>
</div>

<!-- END CONTAINER -->
<!-- BEGIN CORE JS FRAMEWORK-->
<script src="{% static " assets/plugins/jquery-1.8.3.min.js" %}"  type="text/javascript"></script>
<script src="{% static " assets/plugins/bootstrap/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/plugins/pace/pace.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/plugins/jquery-validation/js/jquery.validate.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/plugins/jquery-lazyload/jquery.lazyload.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/js/login_v2.js" %}" type="text/javascript"></script>
<!-- BEGIN CORE TEMPLATE JS -->
<!-- END CORE TEMPLATE JS -->

</body>

</html>
			


templates/dashboard/login_template.html
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

	<title>T-Bio - Dashboard</title>

	<meta charset="utf-8" />
	<meta name="description" content="" />
	<meta name="author" content="" />		
	<meta name="viewport" content="width=device-width,initial-scale=1" />
	
	<link rel="stylesheet" href="{% static "stylesheets/reset.css" %}" type="text/css" media="screen" title="no title" />
	<link rel="stylesheet" href="{% static "stylesheets/text.css" %}" type="text/css" media="screen" title="no title" />
	<link rel="stylesheet" href="{% static "stylesheets/buttons.css" %}" type="text/css" media="screen" title="no title" />
	<link rel="stylesheet" href="{% static "stylesheets/theme-default.css" %}" type="text/css" media="screen" title="no title" />
	<link rel="stylesheet" href="{% static "stylesheets/login.css" %}" type="text/css" media="screen" title="no title" />
</head>

<body>

<div id="login">
	<h1>Dashboard</h1>
	<div id="login_panel">
		<form action="/dashboard/login" method="post" accept-charset="utf-8">		
        	{% csrf_token %}
			<div class="login_fields">
				<div class="field">
					<label for="email">Email</label>
					<input type="text" name="email" value="" id="email" tabindex="1" placeholder="email@example.com" />		
				</div>
			
				<div class="field">
					<label for="password">Password <small><a href="javascript:;">Forgot Password?</a></small></label>
					<input type="password" name="password" value="" id="password" tabindex="2" placeholder="password" />			
				</div>
			</div> <!-- .login_fields -->
			
			<div class="login_actions">
				<button type="submit" class="btn btn-primary" tabindex="3">Login</button>
			</div>
		</form>
	</div> <!-- #login_panel -->		
</div> <!-- #login -->

<script src="{% static "javascripts/all.js" %}"></script>
</body>
</html>

templates/dashboard/register.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<meta charset="utf-8" />
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="" name="description" />
<meta content="" name="author" />
<!-- BEGIN CORE CSS FRAMEWORK -->
<link href="{% static "assets/plugins/pace/pace-theme-flash.css" %}" rel="stylesheet" type="text/css" media="screen"/>
<link href="{% static "assets/plugins/boostrapv3/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/plugins/boostrapv3/css/bootstrap-theme.min.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/plugins/font-awesome/css/font-awesome.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/animate.min.css" %}" rel="stylesheet" type="text/css"/>
<!-- END CORE CSS FRAMEWORK -->
<!-- BEGIN CSS TEMPLATE -->
<link href="{% static "assets/css/style.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/responsive.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "assets/css/custom-icon-set.css" %}" rel="stylesheet" type="text/css"/>
<!-- END CSS TEMPLATE -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="error-body no-top lazy"  data-original="{% static "assets/img/work.jpg" %} "  style="background-image: url('{% static "assets/img/work.jpg" %}')"> 
<div class="container">
  <div class="row login-container animated fadeInUp">  
        <div class="col-md-7 col-md-offset-2 tiles white no-padding">
		 <div class="p-t-30 p-l-40 p-b-20 xs-p-t-10 xs-p-l-10 xs-p-b-10"> 
          <h2 class="normal">Nuevo Usuario</h2>
          <p class="p-b-20">Prevenir siempre es mejor.</p>
        </div>
		<div class="tiles grey p-t-20 p-b-20 text-black">
		
              
    <form action="/dashboard/register/" method="post" class="animated fadeIn" > 
              
          <div class="row form-row m-l-20 m-r-20 xs-m-l-10 xs-m-r-10">
              
              {% csrf_token %}
              
              <div class="col-md-6 col-sm-6 ">
                <input id="id_username" maxlength="30" name="username" type="text" class="form-control" placeholder="Nombre de Usuario" >
              </div>             
              
              <div class="col-md-6 col-sm-6 ">
                <input id="id_email" name="email" type="email" class="form-control" placeholder="Email" >
              </div>             
              
              <div class="col-md-6 col-sm-6 ">
                <input id="id_name" name="name" type="text" class="form-control" placeholder="Nombre" >
              </div>             
              
              <div class="col-md-6 col-sm-6 ">
                <input id="id_last_name" name="last_name" type="text" class="form-control" placeholder="Apellido" >
              </div>
              							
              <div class="col-md-6 col-sm-6 ">

                  <select  id="id_genre" name="genre" class="select2 form-control select2-offscreen" tabindex="-1">
                          <option value="">Genero...</option>
                          <option value="1">Hombre</option>
                          <option value="2">Mujer</option>
                  </select>
              
              </div>
              
              <div class="col-md-6 col-sm-6">
                <input id="id_date_birth" name="date_birth" type="text" class="form-control" placeholder="Fecha Nacimiento" >
              </div>

              <div class="col-md-6 col-sm-6 ">
                <input id="id_password1" name="password1" type="password"  class="form-control" placeholder="Clave" >
              </div>             
              
              <div class="col-md-6 col-sm-6 ">
                <input id="id_password2" name="password2" type="password"  class="form-control" placeholder="Confirma Clave" >
              </div>             
              
      			<div class="login_actions">
              	&nbsp;&nbsp;&nbsp;&nbsp;
               <button type="submit" class="btn btn-info btn-cons" id="register_toggle"> Crear Cuenta</button>

            </div>

          </div>
              
    </form>
    <!--
    <h2>Register Demo<h2>
    
    <form action="/dashboard/register/" method="post"> {% csrf_token %}
      {{form}}
    <input type="submit" value="Register" />
    
    </form>
    -->

		</div>   
      </div>   
  </div>
</div>

<!-- END CONTAINER -->
<!-- BEGIN CORE JS FRAMEWORK-->
<script src="{% static " assets/plugins/jquery-1.8.3.min.js" %}"  type="text/javascript"></script>
<script src="{% static " assets/plugins/bootstrap/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/plugins/pace/pace.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/plugins/jquery-validation/js/jquery.validate.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/plugins/jquery-lazyload/jquery.lazyload.min.js" %}" type="text/javascript"></script>
<script src="{% static " assets/js/login_v2.js" %}" type="text/javascript"></script>
<!-- BEGIN CORE TEMPLATE JS -->
<!-- END CORE TEMPLATE JS -->

</body>

</html>
			

templates/dashboard/test.html
{% extends 'base_dashboard.html' %}
{% block content %}
<h1>hello world!</h1>
{% endblock %}